openapi: 3.0.0
info:
  description: Moonraker API
  version: "1.0.0"
  title: CNAB Moonraker API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: getters
    description: All endpoints to retrieve data
paths:
  /claims:
    get:
      tags:
        - getters
      summary: gets claims.json file
      operationId: claims
      description: |
        Get all claims
      responses:
        '200':
          description: claims returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Claim'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Error'
                  
        '500':
          description: server error
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Error'
components:
  schemas:
    Claim:
      type: object
      properties:
        bundle:
          type: object
          format: uuid
          properties:
            credentials:
              type: object
            images:
              type: object
            invocationImages:
              type: array
              items:
                type: object
                properties:
                  image:
                    type: string
                  imageType:
                    type: string
            name:
              type: string
            outputs:
              type: object
              properties:
                clientCert:
                  type: object
                  properties:
                    definition:
                      type: string
                    path:
                      type: string
            "parameters":
              type: object
            schemaVersion:
              type: string
            "version":
              type: string
        created:
          type: string
        custom:
          type: object
        modified:
          type: string
        name:
          type: string
        outputs:
          type: object
          properties:
            clientCert:
              type: string
        "parameters":
          type: object
        result:
          type: object
          properties:
            action:
              type: string
            message:
              type: string
            status:
              type: string
        revision:
          type: string
          description: An ULID that MUST change each time the release is modified.
    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: error code
        message:
          type: string
          description: error message
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/gabecoelho/moonraker/1.0.0